version: '3.7'

services:

    postgres:
        container_name: postgres_container
        image: postgres:latest

        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata

        volumes:
            - ./initdb:/docker-entrypoint-initdb.d
            - .:/var/lib/postgresql/data

        ports:
            - ${POSTGRES_PORT:-5432}:5432

        restart: unless-stopped

        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 2G

        networks:
            - postgres

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:latest

        depends_on:
            - postgres

        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_CONFIG_SERVER_MODE: 'False'

        volumes:
            - ./pgadmin:/var/lib/pgadmin

        ports:
            - ${PGADMIN_PORT:-5050}:80

        networks:
            - postgres

        restart: unless-stopped

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - '6379:6379'
        volumes:
          - ./redisDB:/data

    coturn:
      image: coturn/coturn
      container_name: coturn
      ports:
        - '3478:3478/tcp'
        - '3478:3478/udp'
        - '5349:5349/tcp'
        - '5349:5349/udp'
        - '49160:49200/udp'

networks:
    postgres:
        driver: bridge
